# Generated by Django 5.1.3 on 2026-03-13 10:56

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="UUID"
                    ),
                ),
                ("name", models.CharField(help_text="The artist name", max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_artist",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="UUID"
                    ),
                ),
                ("name", models.CharField(help_text="The album name", max_length=100)),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        help_text="The year the album was released",
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(9999),
                        ],
                    ),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        help_text="The artist that produced the album",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="albums",
                        to="grunge_app.artist",
                    ),
                ),
            ],
            options={
                "ordering": ("artist", "year", "name"),
            },
        ),
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="UUID"
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="The playlist name", max_length=100),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_playlists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="UUID"
                    ),
                ),
                ("name", models.CharField(help_text="The track name", max_length=100)),
                (
                    "number",
                    models.PositiveSmallIntegerField(
                        help_text="The track number on the album"
                    ),
                ),
                (
                    "album",
                    models.ForeignKey(
                        help_text="The album this track appears on",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to="grunge_app.album",
                    ),
                ),
            ],
            options={
                "ordering": ("number", "name"),
            },
        ),
        migrations.CreateModel(
            name="PlaylistTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        help_text="1-based position",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "playlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playlist_tracks",
                        to="grunge_app.playlist",
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="grunge_app.track",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
            },
        ),
        migrations.AddField(
            model_name="playlist",
            name="tracks",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tracks that appear in this playlist (in order).",
                related_name="playlists",
                through="grunge_app.PlaylistTrack",
                to="grunge_app.track",
            ),
        ),
        migrations.AddIndex(
            model_name="artist",
            index=models.Index(fields=["name"], name="grunge_app__name_de991d_idx"),
        ),
        migrations.AddIndex(
            model_name="album",
            index=models.Index(
                fields=["artist", "year", "name"], name="grunge_app__artist__42eb75_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="track",
            index=models.Index(
                fields=["number", "name"], name="grunge_app__number_f32453_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="track",
            constraint=models.UniqueConstraint(
                fields=("album", "number"), name="unique_album_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="playlisttrack",
            constraint=models.UniqueConstraint(
                fields=("playlist", "order"), name="unique_playlist_order"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="playlisttrack",
            unique_together={("playlist", "track")},
        ),
        migrations.AddIndex(
            model_name="playlist",
            index=models.Index(fields=["name"], name="grunge_app__name_c82b1e_idx"),
        ),
    ]
